# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18j85quc55MlRc4wWGKPx0xS1FskM8_97
"""

import streamlit as st
import pandas as pd
import joblib

# =============================
# CONFIG
# =============================
st.set_page_config(
    page_title="Prediksi Kesehatan Mental Remaja",
    page_icon="🧠",
    layout="wide"
)

# =============================
# LOAD MODEL
# =============================
model = joblib.load("model.pkl")

# =============================
# CSS
# =============================
st.markdown("""
<style>

.main{
background:#F5F7FA;
}

.block-container{
padding-top:2rem;
}

.title{
text-align:center;
font-size:45px;
font-weight:bold;
color:#1565C0;
}

.subtitle{
text-align:center;
color:gray;
font-size:18px;
margin-bottom:20px;
}

div.stButton > button{
width:100%;
height:60px;
font-size:22px;
background:#1565C0;
color:white;
border-radius:10px;
border:none;
}

div.stButton > button:hover{
background:#0D47A1;
color:white;
}

.metric{
padding:15px;
background:white;
border-radius:10px;
box-shadow:0px 2px 8px rgba(0,0,0,0.1);
}

</style>
""", unsafe_allow_html=True)

# =============================
# HEADER
# =============================

st.markdown("<div class='title'>🧠 Prediksi Kesehatan Mental Remaja</div>", unsafe_allow_html=True)

st.markdown("<div class='subtitle'>Machine Learning menggunakan Decision Tree Classifier</div>", unsafe_allow_html=True)

st.write("")

# =============================
# SIDEBAR
# =============================

st.sidebar.image("https://cdn-icons-png.flaticon.com/512/3771/3771417.png", width=120)

st.sidebar.title("Tentang")

st.sidebar.write("""
Aplikasi ini digunakan untuk memprediksi
indikasi kesehatan mental remaja berdasarkan
aktivitas media sosial dan gaya hidup.

Model :
- Decision Tree

Input :
- 13 fitur

Output :
- Sehat
- Berisiko
""")

# =============================
# INPUT
# =============================

left,right=st.columns(2)

with left:

    age=st.number_input("Umur",15,30,18)

    gender=st.selectbox(
        "Gender",
        ["Perempuan","Laki-laki"]
    )

    jam_sosmed=st.slider(
        "Jam Sosial Media",
        0.0,15.0,5.0
    )

    jam_tidur=st.slider(
        "Jam Tidur",
        0.0,12.0,7.0
    )

    menatap_layar=st.slider(
        "Screen Time Sebelum Tidur",
        0.0,10.0,2.0
    )

    aktivitas_fisik=st.slider(
        "Aktivitas Fisik",
        0.0,10.0,5.0
    )

    level_sosialisasi=st.slider(
        "Level Sosialisasi",
        0.0,10.0,5.0
    )

with right:

    stress_level=st.slider(
        "Stress Level",
        0.0,10.0,5.0
    )

    level_cemas=st.slider(
        "Level Cemas",
        0.0,10.0,5.0
    )

    level_kecanduan=st.slider(
        "Level Kecanduan",
        0.0,10.0,5.0
    )

    skor_kesehatan_mental=st.slider(
        "Skor Mental",
        0.0,100.0,50.0
    )

    sleep_quality=st.slider(
        "Kualitas Tidur",
        0.0,10.0,7.0
    )

    status_kesehatan_digital=st.selectbox(
        "Status Digital Wellbeing",
        ["Buruk","Baik"]
    )

# =============================
# ENCODING
# =============================

gender=1 if gender=="Laki-laki" else 0

status_kesehatan_digital=1 if status_kesehatan_digital=="Baik" else 0

# =============================
# DATAFRAME
# =============================

data=pd.DataFrame({

'age':[age],
'gender':[gender],
'jam_sosmed':[jam_sosmed],
'jam_tidur':[jam_tidur],
'menatap_layar':[menatap_layar],
'aktivitas_fisik':[aktivitas_fisik],
'level_sosialisasi':[level_sosialisasi],
'stress_level':[stress_level],
'level_cemas':[level_cemas],
'level_kecanduan':[level_kecanduan],
'skor_kesehatan_mental':[skor_kesehatan_mental],
'sleep_quality':[sleep_quality],
'status_kesehatan_digital':[status_kesehatan_digital]

})

# =============================
# BUTTON
# =============================

if st.button("🔍 Prediksi Sekarang"):

    hasil=model.predict(data)[0]

    st.write("")

    st.subheader("Hasil Prediksi")

    if hasattr(model,"predict_proba"):

        prob=model.predict_proba(data)[0]

        if hasil==1:
            persen=prob[1]*100
        else:
            persen=prob[0]*100

        st.progress(int(persen))

        st.metric("Keyakinan Model",f"{persen:.2f}%")

    if hasil==1:

        st.error("⚠️ Remaja Berisiko Mengalami Gangguan Kesehatan Mental")

    else:

        st.success("✅ Kondisi Kesehatan Mental Baik")

    st.write("")

    st.subheader("Data Input")

    st.dataframe(data,use_container_width=True)

    st.write("")

    st.info("Hasil prediksi hanya sebagai alat bantu dan bukan diagnosis medis.")