# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18j85quc55MlRc4wWGKPx0xS1FskM8_97
"""

import streamlit as st
import joblib
import pandas as pd

# Load model
model = joblib.load("model.pkl")

st.set_page_config(page_title="Prediksi", page_icon="📊")

st.title("Aplikasi Prediksi")
st.write("Masukkan data berikut:")

# Ganti sesuai fitur model
fitur1 = st.number_input("Fitur 1", value=0.0)
fitur2 = st.number_input("Fitur 2", value=0.0)
fitur3 = st.number_input("Fitur 3", value=0.0)
fitur4 = st.number_input("Fitur 4", value=0.0)

if st.button("Prediksi"):
    data = pd.DataFrame([[fitur1, fitur2, fitur3, fitur4]],
                        columns=["fitur1", "fitur2", "fitur3", "fitur4"])

    hasil = model.predict(data)

    st.success(f"Hasil Prediksi: {hasil[0]}")