# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18j85quc55MlRc4wWGKPx0xS1FskM8_97
"""

import streamlit as st
import pandas as pd
import joblib

# ====================================
# Konfigurasi Halaman
# ====================================
st.set_page_config(
    page_title="Prediksi Kesehatan Mental Remaja",
    page_icon="🧠",
    layout="wide"
)

# ====================================
# Load Model
# ====================================
model = joblib.load("model.pkl")

# ====================================
# CSS
# ====================================
st.markdown("""
<style>
.main{
    background-color:#F5F7FA;
}
.title{
    text-align:center;
    font-size:40px;
    color:#1E88E5;
    font-weight:bold;
}
.subtitle{
    text-align:center;
    color:gray;
    font-size:18px;
}
.result{
    padding:15px;
    border-radius:10px;
    font-size:20px;
    font-weight:bold;
}
</style>
""", unsafe_allow_html=True)

st.markdown("<div class='title'>🧠 Prediksi Kesehatan Mental Remaja</div>", unsafe_allow_html=True)
st.markdown("<div class='subtitle'>Machine Learning - Decision Tree / Logistic Regression</div>", unsafe_allow_html=True)

st.write("---")

# ====================================
# Sidebar
# ====================================
st.sidebar.header("Informasi")

st.sidebar.info("""
Aplikasi ini digunakan untuk memprediksi
kemungkinan depresi pada remaja berdasarkan
karakteristik penggunaan media sosial
dan gaya hidup.

Dataset:
- Usia
- Gender
- Jam Sosmed
- Platform
- Jam Tidur
- Screen Time
- Akademik
- Aktivitas Fisik
- Sosialisasi
- Stress
- Kecemasan
- Kecanduan
- Skor Mental
- Status Digital
""")

# ====================================
# Form Input
# ====================================

col1, col2 = st.columns(2)

with col1:

    usia = st.number_input("Usia",18,30,20)

    gender = st.selectbox(
        "Gender",
        [0,1],
        format_func=lambda x:"Laki-laki" if x==1 else "Perempuan"
    )

    jam_sosmed = st.slider(
        "Jam Sosial Media",
        0.0,
        15.0,
        5.0
    )

    platform = st.number_input("Platform Usage",0,10,1)

    jam_tidur = st.slider(
        "Jam Tidur",
        1.0,
        12.0,
        7.0
    )

    menatap_layar = st.slider(
        "Screen Time Sebelum Tidur",
        0.0,
        10.0,
        2.0
    )

    akademik = st.slider(
        "Nilai Akademik",
        0.0,
        100.0,
        80.0
    )

with col2:

    aktivitas_fisik = st.slider(
        "Aktivitas Fisik",
        0.0,
        10.0,
        5.0
    )

    level_sosialisasi = st.slider(
        "Level Sosialisasi",
        0.0,
        10.0,
        5.0
    )

    stress_level = st.slider(
        "Stress Level",
        0.0,
        10.0,
        5.0
    )

    level_cemas = st.slider(
        "Level Kecemasan",
        0.0,
        10.0,
        5.0
    )

    level_kecanduan = st.slider(
        "Level Kecanduan",
        0.0,
        10.0,
        5.0
    )

    skor_kesehatan_mental = st.slider(
        "Skor Kesehatan Mental",
        0.0,
        100.0,
        50.0
    )

    status_kesehatan_digital = st.selectbox(
        "Status Digital Wellbeing",
        [0,1]
    )

# ====================================
# Prediksi
# ====================================

if st.button("🔍 Prediksi", use_container_width=True):

    data = pd.DataFrame({
        "usia":[usia],
        "gender":[gender],
        "jam_sosmed":[jam_sosmed],
        "platform":[platform],
        "jam_tidur":[jam_tidur],
        "menatap_layar":[menatap_layar],
        "akademik":[akademik],
        "aktivitas_fisik":[aktivitas_fisik],
        "level_sosialisasi":[level_sosialisasi],
        "stress_level":[stress_level],
        "level_cemas":[level_cemas],
        "level_kecanduan":[level_kecanduan],
        "skor_kesehatan_mental":[skor_kesehatan_mental],
        "status_kesehatan_digital":[status_kesehatan_digital]
    })

    hasil = model.predict(data)[0]

    st.write("## Hasil Prediksi")

    if hasil == 1:
        st.error("⚠️ Terindikasi Depresi")
    else:
        st.success("✅ Tidak Terindikasi Depresi")

    st.write("### Data Input")
    st.dataframe(data)